name: Run Selenium Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run Selenium tests
      run: mvn test

    - name: Upload Surefire Report
      uses: actions/upload-artifact@v3
      with:
        name: surefire-report
        path: target/surefire-reports
